services:
  application:
    image: 'sharashbarash/dockerhub:app'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/postgres
      MINIO_URL: http://minio:9000
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    networks:
      - enrollment


  postgres:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - enrollment
  minio:
    image: 'bitnami/minio'
    networks:
      - enrollment
    volumes:
      - ~/data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_DEFAULT_BUCKETS: data

networks:
  enrollment:
    driver: bridge