spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  url: http://127.0.0.1:9000
  accessKey: minio
  secretKey: miniominio
  bucket:
    name: data

